### ISSUE TITLE
Jinja variable 'hdfs_repl_override' is undefined

### ISSUE THREAD

**Issue by alex-dot** [saltstack-formulas/hadoop-formula#13]
On a fresh install, I get the following error when highstating the minions:

```
ID: /etc/hadoop/conf/hdfs-site.xml
    Function: file.managed
      Result: False
     Comment: Unable to manage file: Jinja variable 'hdfs_repl_override' is undefined
     Started: 14:04:47.055940
    Duration: 1270.958 ms
     Changes:   
```
