### ISSUE TITLE
Rendering SLS 'base:hadoop.hdfs' failed: Jinja variable No first item, sequence was empty.

### ISSUE THREAD

**Issue by kitplummer** [saltstack-formulas/hadoop-formula#20]
I'm pretty sure it's my pillar config, but I can't get it.  Anybody else see this when trying to use hadoop.hdfs?

```yaml
hdfs:
  config:
    hdfs-site:
      dfs.datanode.synconclose:
        value: true
      dfs.durable.sync:
        value: true
      dfs.permission:
        value: false
    namenode_http_port: 50070
    namenode_port: 8020
    secondarynamenode_http_port: 50090
  datanode_target: "roles:hadoop_slave"
  namenode_target: "roles:hadoop_master"
```

**Comment by sroegner** [comment]
What happens if you try to run completely without the pillar block?

**Comment by kitplummer** [comment]
It still happens.  I've made a little bit of progress though.

Caveat - I'm trying to get a master and slave working under Vagrant and two
VMs.  It boils down to being able to resolve this:

```
{%- set namenode_host       = salt['mine.get'](namenode_target,
'network.interfaces', expr_form=targeting_method)|first %}
```

The error is basically saying that first can't return anything because
there isn't anything there at all.  I have the role getting set in the
minion config, but I'm not sure how to get the mine_functions stuff to work
in this enviro.

**Comment by sroegner** [comment]
You might have guessed that what the code is trying to do is to collect the list of hosts that match expression and targeting_method (in your case the default - grains).
I always use a saltmaster - even in vagrant so I cannot speak to the chances of querying salt mine without one. What you could try is change "hadoop:targeting_method" to something like compound and then adapt the targets to that like below:

    hadoop:
      targeting_method: compound
    hdfs:
      datanode_target: "G@hostname:my_vagrant_datanode"
      namenode_target: "G@hostname:my_vagrant_namenode"
      config:
        hdfs-site:
          dfs.datanode.synconclose:
            value: true
          dfs.durable.sync:
            value: true
          dfs.permission:
            value: false
        namenode_http_port: 50070
        namenode_port: 8020
        secondarynamenode_http_port: 50090

**Comment by kitplummer** [comment]
Ah.  That might be better/easier than what I ended up doing:

```
{%- set namenode_host       = gc.get('namenode_host',
pc.get('namenode_host', salt['mine.get'](namenode_target,
'network.interfaces', expr_form=targeting_method))) %}
{%- set datanode_hosts      = gc.get('datanode_hosts',
pc.get('datanode_hosts', salt['mine.get'](datanode_target,
'network.interfaces', expr_form=targeting_method).keys())) %}
```

And manually spelling 'em out in the pillar config:

```yaml
    namenode_host: 192.168.100.100
    datanode_hosts: [192.168.100.200]
```

**Comment by blbradley** [comment]
I'm experiencing this too right out of the box. I have tried with and without the pillar block from the example. Can we call it a bug? Even if it is just a documentation issue.

**Comment by blbradley** [comment]
FWIW, I'm not using a masterless setup.

**Comment by sroegner** [comment]
@blbradley Can you share the result of 'salt \* grains.get roles' ?

**Comment by blbradley** [comment]
I have this working now. My minion config did have the roles set but was still getting this. I am not able to reproduce again.

Can this error be put in a troubleshooting section? It's hard to debug because no real contextual info (line number, rendered jinja) is given.

**Comment by blbradley** [comment]
I'll do it if someone says it's alright.

**Comment by puneetk** [comment]
send a pull request with the update

**Comment by lextoumbourou** [comment]
I ran into the same issue. I had my Pillar conf setup like this:

``` 
hdfs:
    namenode_target: "role:hadoop-namenode"
    datanode_target: "role:hadoop-datanode"
```

excepting the default grain matching to work, but it doesn't seem to? I was getting the ``Jinja variable No first item, sequence was empty.`` error.

I changed the Pillar to this:

```
hadoop:
    targeting_method: compound

 hdfs:
   namenode_target: "G@role:hadoop-namenode"
   datanode_target: "G@role:hadoop-datanode"
```

and it worked, though I'm not sure if it was the config change or if Salt cleared its cache or something?
