### ISSUE TITLE
confusing /etc/hadoop being recreated post orchestration

### ISSUE THREAD

**Issue by hortovanyi** [saltstack-formulas/hadoop-formula#26]
Am trying to install Apache Hadoop 2.7.1.

Not sure why I've got a conf-2.2.0 & conf.dist directory under /etc/hadoop with .conf linked to /etc/alternatives/hadoop-conf-link??

```
nick@fig:/etc/hadoop$ ls -lat
total 28
drwxr-xr-x 147 root root 12288 Jul 16 16:59 ..
drwxr-xr-x   2 root root  4096 Jul 16 15:59 conf-2.7.1
drwxr-xr-x   2 root root  4096 Jul 16 13:46 conf-2.2.0
drwxr-xr-x   5 root root  4096 Jul 16 13:46 .
lrwxrwxrwx   1 root root    34 Jul 16 13:05 conf -> /etc/alternatives/hadoop-conf-link
drwxr-xr-x   2 root root  4096 Jun 29 16:15 conf.dist
```

have tried removing the offending directories and linking conf -> ./conf-2.7.1. However after a reboot it returns to the above configuration without a salt run.

**Comment by sroegner** [comment]
Can you share your pillar settings please?

**Comment by hortovanyi** [comment]
This is what I'm using presently
```
java_home:
  /usr/lib/jvm/java-7-openjdk-amd64

hadoop:
  version: apache-2.7.1 # ['apache-1.2.1', 'apache-2.2.0', 'hdp-1.3.0', 'hdp-2.2.0', 'cdh-4.5.0', 'cdh-4.5.0-mr1']
  versions:
    apache-2.7.1:
      version: 2.7.1
      version_name: hadoop-2.7.1
      source_url: http://apache.mirror.digitalpacific.com.au/hadoop/common/hadoop-2.7.1/hadoop-2.7.1.tar.gz
      major_version: '2'
  targeting_method: grain # [compound, glob] also supported
  users:
    hadoop: 6000
    hdfs: 6001
    mapred: 6002
    yarn: 6003
  config:
    directory: /etc/hadoop/conf
    core-site:
      io.native.lib.available:
        value: true
      io.file.buffer.size:
        value: 65536
      fs.trash.interval:
        value: 60

hdfs:
  namenode_target: "roles:hadoop_master" # Specify compound matching string to match all your namenodes
  datanode_target: "roles:hadoop_slave" # Specify compound matching string to match all your datanodes e.g. if you were to use pillar I@datanode:true
  config:
    namenode_port: 8020
    namenode_http_port: 50070
    secondarynamenode_http_port: 50090
    # the number of hdfs replicas is normally auto-configured for you in hdfs.settings
    # according to the number of available datanodes
    # replication: 1
    hdfs-site:
      dfs.permission:
        value: false
      dfs.durable.sync:
        value: true
      dfs.datanode.synconclose:
        value: true

mapred:
  jobtracker_target: "roles:hadoop_master"
  tasktracker_target: "roles:hadoop_slave"
  config:
    jobtracker_port: 9001
    jobtracker_http_port: 50030
    jobhistory_port: 10020
    jobhistory_webapp_port: 19888
    history_dir: /mr-history
    mapred-site:
      mapred.map.memory.mb:
        value: 1536
      mapred.map.java.opts:
        value: -Xmx1024M
      mapred.reduce.memory.mb:
        value: 3072
      mapred.reduce.java.opts:
        value: -Xmx1024m
      mapred.task.io.sort.mb:
        value: 512
      mapred.task.io.sort.factor:
        value: 100
      mapred.reduce.shuffle.parallelcopies:
        value: 50

# you only have to configure the capacity-scheduler section to the extent you need it - if omitted the 
# resulting file (HADOOP_CONF/capacity-scheduler.xml) will just remain empty (no defaults)
yarn:
  resourcemanager_target: "roles:hadoop_master"
  nodemanager_target: "roles:hadoop_slave"
  config:
    yarn-site:
      yarn.nodemanager.aux-services:
        value: mapreduce_shuffle
      yarn.nodemanager.aux-services.mapreduce.shuffle.class:
        value: org.apache.hadoop.mapred.ShuffleHandler
```
