### ISSUE TITLE
Provision hadoop fails with service not running errors.

### ISSUE THREAD

**Issue by nocturnaltortoise** [saltstack-formulas/hadoop-formula#40]
When I run salt-run state.orchestrate provision_hadoop, I get no errors except ones saying the service isn't running: 

On the hadoop_slave:
```
ID: hdfs-services
Function: service.running
Name: hadoop-datanode
Result: False
Comment: The named service hadoop-datanode is not available
Started: 14:07:18.029442
Duration: 18.218 ms
Changes: 

```
and on the hadoop_master:
```
----------
ID: hdfs-nn-services
Function: service.running
Name: hadoop-namenode
Result: False
Comment: The named service hadoop-namenode is not available
Started: 14:07:24.731055
Duration: 18.735 ms
Changes:   
 ----------
ID: hdfs-nn-services
Function: service.running
Name: hadoop-secondarynamenode
Result: False
Comment: The named service hadoop-secondarynamenode is not available
Started: 14:07:24.750181
Duration: 18.097 ms
Changes:   
```

I'm using the example provision_hadoop.sls file:
```yaml
prep:
  salt.state:
    - tgt: '*'
    - sls:
      - hostsfile
      - hostsfile.hostname
      - ntp.server
      - sun-java
      - sun-java.env

# the target for hadoop_services only means where the binaries and config will end up
# targetting for service startup and configuration is done on the service level in pillars

hadoop_services:
  salt.state:
    - tgt: 'G@roles:hadoop_master or G@roles:hadoop_slave'
    - tgt_type: compound
    - require:
      - salt: prep
    - sls:
      - hadoop
      - hadoop.hdfs
      - hadoop.yarn
```

I have this in my pillar: 
```yaml
hadoop:
  targeting_method: compound
hdfs:
  config:
    hdfs-site:
      dfs.datanode.synconclose:
        value: true
      dfs.durable.sync:
        value: true
      dfs.permission:
        value: false
    namenode_http_port: 50070
    namenode_port: 8020
    secondarynamenode_http_port: 50090
  datanode_target: "G@roles:hadoop_slave"
  namenode_target: "G@roles:hadoop_master"
```
This in the /etc/salt/grains file on the hadoop_master:
```yaml
roles:
  - hadoop_master
hdfs_data_disks:
  - /hdfs
yarn_data_disks:
  - /yarn
```
and this in the grains file on the hadoop_slave:
```yaml
roles:
  - hadoop_slave
hdfs_data_disks:
  - /hdfs
yarn_data_disks:
  - /yarn
```

Is there something else I need to specify in the pillar variables to get the services to start? Or is there some other issue?

**Comment by sroegner** [comment]
Thank you for your issue report - could you please add the output of `salt --versions-report` from one of your salt nodes?

**Comment by nocturnaltortoise** [comment]
Here's the output of `salt --versions-report`:
```
Salt Version:
           Salt: 2016.3.1
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: 3.5.0
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.24.0
         Python: 2.7.12 (default, Jul  1 2016, 15:12:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.5.7-std-3
         system: Linux
        version: Ubuntu 16.04 xenial
```
And the output of `salt-call pillar.items`:
```
local:
    ----------
    hadoop:
        ----------
        targeting_method:
            compound
    hdfs:
        ----------
        config:
            ----------
            hdfs-site:
                ----------
                dfs.datanode.synconclose:
                    ----------
                    value:
                        True
                dfs.durable.sync:
                    ----------
                    value:
                        True
                dfs.permission:
                    ----------
                    value:
                        False
            namenode_http_port:
                50070
            namenode_port:
                8020
            secondarynamenode_http_port:
                50090
        datanode_target:
            G@roles:hadoop_slave
        namenode_target:
            G@roles:hadoop_master
```

**Comment by sroegner** [comment]
Ok, thank you. I have since tried to reproduce the problem and was unable to do so - on CentOS. I'll go back and try Ubuntu.

**Comment by simonclausen** [comment]
I may be experiencing a similar issue, but on Debian 8, with a non-HA setup:

On the "roles:hadoop_master" node:
```
----------
          ID: hdfs-nn-services
    Function: service.running
        Name: hadoop-namenode
      Result: False
     Comment: The named service hadoop-namenode is not available
     Started: 09:05:16.060554
    Duration: 7.192 ms
     Changes:   
----------
          ID: hdfs-nn-services
    Function: service.running
        Name: hadoop-secondarynamenode
      Result: False
     Comment: The named service hadoop-secondarynamenode is not available
     Started: 09:05:16.067983
    Duration: 6.918 ms
     Changes:
----------
          ID: hadoop-historyserver
    Function: service.running
      Result: False
     Comment: The named service hadoop-historyserver is not available
     Started: 09:05:27.280336
    Duration: 9.237 ms
     Changes:
----------
          ID: hadoop-resourcemanager
    Function: service.running
      Result: False
     Comment: The named service hadoop-resourcemanager is not available
     Started: 09:05:27.326274
    Duration: 7.811 ms
     Changes:
```
_Successful output removed_

On "roles:hadoop_slave" nodes:
```
----------
          ID: hdfs-services
    Function: service.running
        Name: hadoop-datanode
      Result: False
     Comment: The named service hadoop-datanode is not available
     Started: 09:17:21.567884
    Duration: 9.101 ms
     Changes:
----------
          ID: hadoop-nodemanager
    Function: service.running
      Result: False
     Comment: The named service hadoop-nodemanager is not available
     Started: 09:17:22.837828
    Duration: 9.214 ms
     Changes:
```
_Successful output removed_

This is with `hadoop`, `hadoop.hdfs` and `hadoop.yarn` states targeted in `top.sls`.

`salt --versions-report`:

```
Salt Version:
           Salt: 2016.3.2
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.5 
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.5
```

**Comment by simonclausen** [comment]
It looks like these errors - at least some of them - were caused by the hostsfile formula doing incorrect configuration of the hosts file, rendering the master unable to contact its own services.

Btw, I ran my exact environment and states on CentOS 7 in stead of Debian 8 with the same results as first posted.

**Comment by nocturnaltortoise** [comment]
You're right, it was the hostsfile formula configuration, I changed my /etc/salt/minion files to:

```
mine_functions:
  network.interfaces: []
  network.ip_addrs:
    - eth1
mine_interval: 2
```
rather than what I had previously which was:
```
mine_functions:
  network.ip_addrs: []
```

All seems to function now, thanks for the help.
