### ISSUE TITLE
Feature request: extend pillar to use in multi cluster deployment

### ISSUE THREAD

**Issue by porunov** [saltstack-formulas/hadoop-formula#48]
Hello @sroegner , 
I would like to provide PR which will extend an existing pillar options with `clusters` option to deploy several hadoop clusters.

I would like to hear your review and whether you like it or not.

If you do, I can provide the PR. If you don't, please, say why.
 
Here is an example of additional parameters in pillar:

```
hdfs:
  clusters:
    cluster1:
      primary_namenode: 192.168.0.101
      secondary_namenode: 192.168.0.102
      journalnodes:
        - 192.168.0.101
        - 192.168.0.102
        - 192.168.0.103
      zookeeper_connection_string: 192.168.0.101:2181,192.168.0.102:2182,192.168.0.103:2183
      datanodes:
        - 192.168.0.104
        - 192.168.0.105
        - 192.168.0.106
    cluster2:
      primary_namenode: 192.168.1.101
      secondary_namenode: 192.168.1.102
      journalnodes:
        - 192.168.1.101
        - 192.168.1.102
        - 192.168.1.103
      zookeeper_connection_string: 192.168.1.101:2181,192.168.1.102:2182,192.168.1.103:2183
      datanodes:
        - 192.168.1.104
        - 192.168.1.105
        - 192.168.1.106
        
mapred:
  clusters:
    cluster1:
      jobtracker: 192.168.0.101
      jobtracker_on_primary_namenode: Flase
      tasktrackers_on_datanodes: False
      tasktrackers:
        - 192.168.0.104
        - 192.168.0.105
        - 192.168.0.106
    cluster2:
      jobtracker: 192.168.1.101
      jobtracker_on_primary_namenode: True
      tasktrackers_on_datanodes: True
      tasktrackers: 
        - 192.168.1.104
        - 192.168.1.105
        - 192.168.1.106
      
yarn:
  clusters:
    cluster1:
      primary_resourcemanager: 192.168.0.101
      secondary_resourcemanager: 192.168.0.102
      resource_manager_on_namenode: True
      nodemanagers_on_datanodes: True
      zookeeper_connection_string: 192.168.0.101:2181,192.168.0.102:2182,192.168.0.103:2183
      nodemanagers:
        - 192.168.0.104
        - 192.168.0.105
        - 192.168.0.106
    cluster2:
      primary_resource_manager: 192.168.0.101
      secondary_resource_manager: 192.168.0.102
      resource_manager_on_namenode: False
      nodemanagers_on_datanodes: False
      zookeeper_connection_string: 192.168.1.101:2181,192.168.1.102:2182,192.168.1.103:2183
      nodemanagers:
        - 192.168.1.104
        - 192.168.1.105
        - 192.168.1.106
```
        
About mapred:
In case `jobtracker_on_primary_namenode` is equal to True, then `jobtracker` parameter isn't used. Job tracker will be installed on primary namenode.
In case `tasktrackers_on_datanodes` is equal to True then task trackers will be also installed on all data nodes (in addition with `tasktrackers` list).
In case there are no `tasktrackers` parameters in the cluster and `tasktrackers_on_datanodes` is set to False, targeting methods will be used.

About yarn:
In case `resourcemanager_on_namenode` is equal to True, then `primary_resource_manager` and `secondary_resource_manager` parameters are ignored. Resource manager will be installed on a primary namenode or on both primary and secondary namenodes if secondary namenode is specified.
In case `nodemanagers_on_datanodes` is equal to True, then `nodemanagers` will be also installed on all data nodes (in addition with `nodemanagers` list).
In case there are no `nodemanagers` parameter in the cluster and `nodemanagers_on_datanodes` is set to False, targeting methods will be used.

`zookeeper_connection_string` is an optional parameter. In case it is empty Hadoop formula will fetch connection string from Zookeeper formula.

About yarn. If you don't want to complicate it, I can remove yarn high availability feature.

Best regards,
Alexandr
